name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      # - name: Run Unit Tests
      #   run: npm run test:unit
        
      # - name: Run Docker Compose and Log to File
      #   run: |
      #     docker-compose -f docker-compose.test.yml up --abort-on-container-exit 2>&1 | tee tests.log

      # - name: Check Docker Compose Exit Code
      #   run: |
      #     exit_code=$?
      #     if [ $exit_code -ne 0 ]; then
      #       echo "Docker Compose failed with exit code $exit_code"
      #       exit 1
      #     fi

      - name: Build Docker Image 
        run: |
          docker build -t crwebappprodwe.azurecr.io/more_frontend:latest .
          echo ${{ secrets.ACR_PASSWORD }} | docker login crwebappprodwe.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker push crwebappprodwe.azurecr.io/more_frontend:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: crwebappprodwe.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Terraform Init
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }} 
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          IMAGE_NAME: "crwebappprodwe.azurecr.io/more_frontend:latest"       

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "image_name=${{ env.IMAGE_NAME }}"
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          IMAGE_NAME: "crwebappprodwe.azurecr.io/more_frontend:latest"
          STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
          STORAGE_ACCOUNT_KEY: ${{ secrets.STORAGE_ACCOUNT_KEY }}
